name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: setup.py

    # these libraries enable testing on Qt on linux
    - name: Install Linux dependencies
      uses: tlambert03/setup-qt-libs@v1

    # workaround for testing Qt on linux
    - name: Workaround for testing Qt on linux
      if: runner.os == 'Linux'
      run: |
        sudo mkdir /usr/bin/platforms
        sudo ln -s /our/local/libqxcb.so /usr/bin/platforms/libqxcb.so

    - name: Install dependencies
      run: |
        pip install -e .
        pip install '.[test]'

    - name: Run flake8
      run: |
        flake8 ./sanpy --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test and generate coverage report
      run: |
        pytest --cov=./tests --cov-report=xml --ignore=./tests/interface ./tests

    # - name: Run unittest
    #   run: |
    #     python -m unittest

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3